import type { SceneSpec } from "./sceneSpec";

export const demoSceneSpec: SceneSpec = {
  title: "AI x Web3 Demo Day Arena",
  theme: "futuristic",
  worldType: "web3_demo_day",
  zones: [
    {
      id: "entrance",
      type: "entrance",
      title: "Builder Gate",
      subtitle: "Prompt to world",
      position: [0, 0, 5],
      color: "#1b2735",
      accent: "#50e3c2",
    },
    {
      id: "main-stage",
      type: "main_stage",
      title: "Main Stage",
      subtitle: "Final demos",
      position: [0, 0, -6],
      color: "#352061",
      accent: "#b785ff",
    },
    {
      id: "zai-track",
      type: "track_zone",
      title: "Z.AI Track",
      subtitle: "Long-horizon agents",
      position: [-5, 0, -1],
      color: "#143946",
      accent: "#58e1ff",
    },
    {
      id: "cobo-track",
      type: "track_zone",
      title: "Cobo Track",
      subtitle: "Agentic wallets",
      position: [5, 0, -1],
      color: "#46361b",
      accent: "#ffd166",
    },
    {
      id: "project-wall",
      type: "project_booth",
      title: "Project Wall",
      subtitle: "Teams and demos",
      position: [-5, 0, -6],
      color: "#22324a",
      accent: "#82aaff",
    },
    {
      id: "sponsor-zone",
      type: "sponsor_zone",
      title: "Sponsor Zone",
      subtitle: "Partner showcases",
      position: [5, 0, -6],
      color: "#3a2437",
      accent: "#ff7ab6",
    },
    {
      id: "timeline",
      type: "timeline",
      title: "Build Timeline",
      subtitle: "Learn, build, submit",
      position: [-7, 0, 4],
      color: "#173828",
      accent: "#8fffbd",
    },
    {
      id: "nft-wall",
      type: "nft_wall",
      title: "Proof Wall",
      subtitle: "NFT and POAP memory",
      position: [7, 0, 4],
      color: "#2c2547",
      accent: "#c4a7ff",
    },
  ],
  web3Proofs: [
    {
      type: "nft_wall",
      title: "Builder Proof Wall",
      source: "mock_metadata",
    },
    {
      type: "wallet_badge",
      title: "Visitor Badge",
      source: "manual",
    },
  ],
};
